version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # CHANGE IT IF IN PRODUCTION
      MYSQL_DATABASE: introduction_web_db
      MYSQL_USER: goku # CHANGE IT IF IN PRODUCTION
      MYSQL_PASSWORD: vegeta # CHANGE IT IF IN PRODUCTION
    ports:
      - "6800:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./app/sql/dbprepare.sql:/docker-entrypoint-initdb.d/dbprepare.sql

volumes:
  mysql_data:
